GET http://localhost:4004/catalog/
Authorization: Basic joe:
###
GET http://localhost:4004/catalog/$metadata
Authorization: Basic joe:
###
GET http://localhost:4004/catalog/Stories
Authorization: Basic joe:
###
GET http://localhost:4004/catalog/userInfo()
Authorization: Basic joe:
###
